media:
  input: public/media
  output: /media

settings:
  hide: true

content:
  - name: albums
    label: Albums
    path: src/_albums
    format: json
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        options:
          autoresize: true
        required: true
        
      - name: body
        label: Body
        type: text

      - name: cover_image
        label: Cover Image
        type: image
        required: true

      - name: release_date
        label: Release Date
        type: date

  - name: gigs
    label: Gigs
    path: src/_gigs
    format: json
    type: collection
    fields:
      - name: gig_uuid
        label: UUID
        type: uuid
        options:
          editable: false
      
      - name: gig_name
        label: Gig Name
        type: text
        options:
          autoresize: true
        required: true

      - name: gig_images
        label: Gig Images
        type: image
        options:
          multiple: true
        required: false

        
    
