media:
  input: public/media
  output: /media

settings:
  hide: true

content:
  - name: releases
    label: Releases
    path: src/_releases
    icon: Disc3
    format: json
    type: collection
    fields:
# option for album or single
    
      - name: title
        label: Title
        type: text
        options:
          rows: 1
          autoresize: true
        required: true
      - name: release_tyoe
        label: Release Type
        type: select
        description: Allows you to specify why type of promotion it is.
        options:
          values:
            - value: album
              label: Album
            - value: single
              label: Single
            - value: ep
              label: EP

      - name: body
        label: Body
        type: text

      - name: cover_image
        label: Cover Image
        type: image
        required: true

      - name: release_date
        label: Release Date
        type: date

  - name: gigs
    label: Gigs
    path: src/_gigs
    icon: Guitar
    format: json
    type: collection
    fields:
          
      - name: gig_name
        label: Gig Name
        type: text
        options:
          rows: 1
          autoresize: true
        required: true

      - name: gig_images
        label: Gig Images
        type: image
        options:
          multiple: true
        required: false

  - name: promotion
    label: Promotion
    path: src/_promotion.json
    type: file
    icon: Smartphone
    format: json
    fields:
      
      - name: promotion_type
        label: Promotion Type
        type: select
        description: Allows you to specify why type of promotion it is.
        options:
          values:
            - value: release
              label: Release
            - value: gig
              label: Gig
      - name: promotion_title
        label: Promotion Title
        type: text
        options:
          rows: 1
        required: true
      - name: promotion_image
        label: Promotion Image
        type: image
        options:
          multiple: false
      - name: promotion_body
        label: Promotion Body
        type: text
        options:
          autoresize: true
      - name: promotion_end
        label: Promotion End
        description: When the promtion ends, will end at 12:01am on the date provided.
        type: date
        required: true
  - name: members
    label: Members
    path: src/_members
    type: collection
    icon: Users
        

# Condition based feilds
  

        
    
