media:
  input: public/media
  output: /media

settings:
  hide: false

content:
  - name: gigs
    label: Gigs
    path: public/_content/_gigs
    icon: Guitar
    format: json
    filename: "{year}-{month}-{day}-{primary}.json"
    type: collection
    fields:
      - name: gig_name
        label: Gig Name
        type: string
        required: true
      - name: gig_body
        label: Gig Body
        type: rich-text
        description: A breif summary of the event!
      - name: gig_date
        label: Gig Date
        type: date
        required: true
      - name: gig_images
        label: Gig Images
        type: image
        options:
          multiple: true
          input: _gigs/{gig_name}
          extentions: ["jpg", "jpeg", "apng", "png", "gif", "svg", "ico", "avif", "bmp", "tif", "tiff", "webp"]
        required: false
  - name: releases
    label: Releases
    path: public/_content/_releases
    icon: Disc3
    filename: "{year}-{month}-{day}-{primary}.json"
    format: json
    type: collection
    fields:
      - name: release_title
        label: Release Title
        type: string
        required: true
        
      - name: release_type
        label: Release Type
        type: select
        description: Allows you to specify why type of promotion it is.
        options:
          values:
            - value: album
              label: Album
            - value: single
              label: Single
            - value: ep
              label: EP

      - name: release_body
        label: Release Body
        type: rich-text
        description: Talk about your release, the people want to hear!
        

      - name: cover_image
        label: Cover Image
        type: image
        options:
          input: _releases
          extentions: ["jpg", "jpeg", "apng", "png", "gif", "svg", "ico", "avif", "bmp", "tif", "tiff", "webp"]
        required: true

      - name: release_date
        label: Release Date
        type: date
  - name: promotion
    label: Promotion
    path: public/_content/_promotion.json
    type: file
    icon: Smartphone
    format: json
    fields:
      - name: promotion_title
        label: Promotion Title
        type: string
        required: true
      - name: promotion_type
        label: Promotion Type
        type: select
        description: Allows you to specify why type of promotion it is.
        options:
          values:
            - value: release
              label: Release
            - value: gig
              label: Gig
      - name: promotion_body
        label: Promotion Body
        type: rich-text
        options:
          autoresize: true
      - name: promotion_image
        label: Promotion Image
        type: image
        options:
          multiple: false
          extentions: ["jpg", "jpeg", "apng", "png", "gif", "svg", "ico", "avif", "bmp", "tif", "tiff", "webp"]
      - name: promotion_end
        label: Promotion End
        description: When the promtion ends, will end at 12:01am on the date provided.
        type: date
        required: true
      - name: promotion_active
        label: Promotion Active
        type: boolean
        default: true
        description: Overwritten by promotion end date.
  - name: members
    label: Band Members
    path: public/_content/_members
    type: collection
    icon: Users
    editorNotes: "All values provided will be pushed to the website, make sure they're formatted and spelt right!"
    format: json
    filename: "{year}-{month}-{day}-{primary}.json"
    fields:
      - name: member_name
        label: Member Name
        type: string
        required: true
      - name: member_role
        label: Member Role
        type: string
      - name: member_blurb
        label: Member Blurb
        type: text
        options:
          rows: 1
          autoresize: true
      - name: member_image
        label: Member Image
        type: image
        options:
          input: _members
          multiple: false
          extentions: ["jpg", "jpeg", "apng", "png", "gif", "svg", "ico", "avif", "bmp", "tif", "tiff", "webp"]
  - name: socials
    label: Socials
    path: public/_content/_socials
    type: collection
    icon: MessageCircle
    format: json
    filename: "{primary}.json"
    fields:
      - name: social_name
        label: Social Name
        type: string
        required: true

      - name: social_icon
        label: Social Icon
        type: icon
        required: true
        
      
        

# Condition based feilds
  

        
    
